FROM openjdk:18-jdk
ARG JAR_FILE=build/libs/connessioni.jar
COPY ${JAR_FILE} connessioni.jar
ENTRYPOINT ["java","-Xmx128m", "-Xms128m","-jar","/connessioni.jar"]
HEALTHCHECK --start-period=30s --interval=10s CMD curl -f http://localhost:8080/actuator/health || exit 1
