FROM openjdk:18-jdk
ARG JAR_FILE=build/libs/enigmi-seguiti.jar
COPY ${JAR_FILE} enigmi-seguiti.jar
ENTRYPOINT ["java","-Xmx128m", "-Xms128m","-jar","/enigmi-seguiti.jar"]
HEALTHCHECK --start-period=30s --interval=10s CMD curl -f http://localhost:8080/actuator/health || exit 1
